name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '30 5 * * 1' # 5:30 AM UTC on Mondays

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --all -- --check
  
  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.2.0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - run: cargo clippy --all
  
  test:
    name: Tests
    needs: [rustfmt, clippy]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust:
        - 1.51.0 # MSRV
        - stable
        - beta
        - nightly

    steps:
    - uses: actions/checkout@v3.2.0
    - name: Install minimal ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
