name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '30 5 * * 1' # 5:30 AM UTC on Mondays

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.toml') }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --all -- --check
  
  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-stable-cargo-${{ hashFiles('**/Cargo.toml') }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - run: cargo clippy --all
  
  test:
    name: Tests
    needs: [rustfmt, clippy]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust:
        - 1.51.0 # MSRV
        - stable
        - beta
        features:
        - default
        - alloc
        exclude:
        - os: macOS-latest # MacOS 12 (and later) doesn't compile with Rust 1.51
          rust: 1.51.0

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Install minimal ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
    - name: Ensure compatible dependencies
      run: |
        cargo update -p serde_json --precise 1.0.64
        cargo update -p serde --precise 1.0.125
        cargo update -p quote --precise 1.0.9
        cargo update -p syn --precise 1.0.72
        cargo update -p proc-macro2 --precise 1.0.26
      if: matrix.rust == '1.51.0'
    - name: Build
      run: cargo build --verbose --no-default-features --features "${{ matrix.features }}"
    - name: Run tests
      run: cargo test --verbose --no-default-features --features "${{ matrix.features }}"
